project_name: flood
release:
  github:
    owner: flood-io
    name: cli
  name_template: '{{.Tag}}'
  prerelease: true

brew:
  github:
    owner: flood-io
    name: homebrew-taps
  folder: Formula
  description: Flood IO Command Line Interface
  homepage: "https://github.com/flood-io/cli"
  install: bin.install "flood"
  test: system bin/"flood", "version"

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  env:
    - CGO_ENABLED=0
  binary: flood
  lang: go

archive:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  # zip is more common for macos
  format_overrides:
    - goos: darwin
      format: zip

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
dist: dist
