
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
    'github.com/jteeuwen/go-bindata/go-bindata'
    ]


[[constraint]]
  branch = "feature/floodchrome"
  name = "github.com/flood-io/go-wrenches"

[[constraint]]
  name="github.com/gogo/protobuf"
  branch="master"

[[constraint]]
  name = "github.com/google/go-querystring"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/tcnksm/go-input"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.1"

[[constraint]]
  name = "github.com/vbauerster/mpb"
  version = "3.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  version = "3.0.7"

[[constraint]]
  name = "github.com/bugsnag/bugsnag-go"
  version = "1.3.0"
